### ISSUE TITLE
Week Two

### ISSUE THREAD

**Issue by searge** [Searge/mipt_oop#2]
## Введение в ООП

- [x] Чем хорошо объектно-ориентированное программирование?
- [x] Отличие класса от объекта
- [x] Отличие интерфейса класса от реализации
- [x] Объектно-ориентированное программирование

## Парадигмы ООП

- [x] Инкапсуляция и полиморфизм в Python
- [x] Парадигмы ООП
- [x] SOLID-принципы
- [x] Принципы и парадигмы ООП

## Разработка системы классов

- [x] Наследование в Python
- [x] Парадигма наследования
- [x] Абстрактные классы и библиотека abc
- [x] Построение схемы наследования
- [x] Programming Assignment: Создание базовых классов
- [x] Создание базовых классов: решение
- [x] UML-нотация и диаграммы классов
- [x] Quiz: UML-нотация

## Рефакторинг кода

- [x] Объектно-ориентированный рефакторинг программ
- [x] Peer-graded Assignment: Создание иерархий классов
- [x] Review Your Peers: Создание иерархий классов
- [x] ReadingКонспект по Неделе 2

**Comment by Searge** [comment]
## Парадигмы ООП

- [x] Инкапсуляция и полиморфизм в Python
- [x] Парадигмы ООП
- [ ] SOLID-принципы
- [ ] Принципы и парадигмы ООП
